'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Bell, House, ChartNoAxesCombined, Newspaper, CalendarDays, BookOpen, ArrowUpRight, ChevronRight, X, Check, Plus, Trash2, RefreshCw, Volume2, Bookmark, Orbit } from 'lucide-react';
import { beijingDate, type Edition, type SavedRecord, type RecordInput } from '../lib/content';
import { words } from '../lib/words';

type Tab='今日'|'投资'|'资讯'|'日常'|'单词';
type Data={editions:Edition[];records:SavedRecord[]};
const navigation=[['今日',House],['投资',ChartNoAxesCombined],['资讯',Newspaper],['日常',CalendarDays],['单词',BookOpen]] as const;
const displayDate=(date:string)=>new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long',timeZone:'Asia/Shanghai'}).format(new Date(date+'T12:00:00+08:00'));
const str=(value:unknown)=>typeof value==='string'?value:'';
declare global { interface Window { firebase?: any; DAYLIGHT_FIREBASE_CONFIG?: Record<string,string> } }
const editionCollection='daylightEditions';
const recordCollection='daylightUsers';
export default function Daylight(){
 const [tab,setTab]=useState<Tab>('今日'),[data,setData]=useState<Data>({editions:[],records:[]}),[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<'brief'|'messages'|'books'|null>(null),[selected,setSelected]=useState<Edition|null>(null),[task,setTask]=useState(''),[stock,setStock]=useState(''),[stockName,setStockName]=useState(''),[revealed,setRevealed]=useState(false),[today,setToday]=useState(beijingDate);
 const dialog=useRef<HTMLDialogElement>(null);
 const cloud=useRef<{auth:any;db:any;user:any}>({auth:null,db:null,user:null});
 const agentState=useRef({data,tab});agentState.current={data,tab};
 useEffect(()=>{
  type Registry={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>unknown};
  const context=(document as Document & {modelContext?:Registry}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:'read_daylight_today',description:'Read the latest daily edition and saved task count displayed by this signed-in personal dashboard.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected empty object');const current=agentState.current;return {tab:current.tab,edition:current.data.editions[0]??null,taskCount:current.data.records.filter(r=>r.kind==='task').length}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort();
 },[]);
 const load=useCallback(async()=>{const {db,user}=cloud.current;if(!db||!user)return null;try{const [editionRows,recordRows]=await Promise.all([db.collection(editionCollection).orderBy('date','desc').limit(30).get(),db.collection(recordCollection).doc(user.uid).collection('records').get()]);const editions=editionRows.docs.map((row:any)=>{const item=row.data();return {...item,receivedAt:item.receivedAt?.toDate?.().toISOString?.()||''} as Edition});const records=recordRows.docs.map((row:any)=>{const item=row.data();return {kind:item.kind,id:item.id,value:item.value} as SavedRecord});setData({editions,records});setError('');return {editions,records}}catch(e){setError(e instanceof Error?e.message:'云端内容暂时无法读取，请重试');return null}finally{setLoading(false)}},[]);
 useEffect(()=>{const firebase=window.firebase;if(!firebase||!window.DAYLIGHT_FIREBASE_CONFIG){setError('日序的云端登录尚未配置完成。');setLoading(false);return}try{if(!firebase.apps.length)firebase.initializeApp(window.DAYLIGHT_FIREBASE_CONFIG);cloud.current.auth=firebase.auth();cloud.current.db=firebase.firestore();const unsubscribe=cloud.current.auth.onAuthStateChanged((user:any)=>{cloud.current.user=user;setSignedIn(Boolean(user));if(user){setLoading(true);void load()}else{setData({editions:[],records:[]});setLoading(false)}});return()=>unsubscribe()}catch{setError('云端登录初始化失败，请稍后重试。');setLoading(false)}},[load]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible'){setToday(beijingDate());void load()}};document.addEventListener('visibilitychange',refresh);const interval=setInterval(refresh,60000);return()=>{document.removeEventListener('visibilitychange',refresh);clearInterval(interval)}},[load]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close()},[modal]);
 async function save(record:RecordInput){if(busy)return false;const {db,user}=cloud.current;if(!db||!user){setError('请先用已授权的 Google 账号登录。');return false}setBusy(true);try{await db.collection(recordCollection).doc(user.uid).collection('records').doc(record.kind+'_'+encodeURIComponent(record.id)).set({kind:record.kind,id:record.id,value:record.value,updatedAt:window.firebase.firestore.FieldValue.serverTimestamp()},{merge:true});setData(old=>({...old,records:[...old.records.filter(x=>x.kind!==record.kind||x.id!==record.id),record as SavedRecord]}));setError('');return true}catch(e){setError(e instanceof Error?e.message:'保存失败，请重试');return false}finally{setBusy(false)}}
 async function remove(record:SavedRecord){const {db,user}=cloud.current;if(!db||!user)return;setBusy(true);try{await db.collection(recordCollection).doc(user.uid).collection('records').doc(record.kind+'_'+encodeURIComponent(record.id)).delete();setData(old=>({...old,records:old.records.filter(x=>x.kind!==record.kind||x.id!==record.id)}))}catch(e){setError(e instanceof Error?e.message:'删除失败，请重试')}finally{setBusy(false)}}
 async function signIn(){try{await cloud.current.auth.signInWithRedirect(new window.firebase.auth.GoogleAuthProvider())}catch{setError('无法跳转到 Google 登录，请稍后重试。')}}
 const latest=data.editions[0],tasks=data.records.filter(r=>r.kind==='task'),stocks=data.records.filter(r=>r.kind==='stock'),books=data.records.filter(r=>r.kind==='book'),read=new Set(data.records.filter(r=>r.kind==='read').map(r=>r.id)),unread=data.editions.filter(e=>!read.has(e.date));
 const todaysTasks=tasks.filter(t=>str(t.value.date)<=today&&!t.value.done||str(t.value.date)===today);
 const reviews=data.records.filter(r=>r.kind==='word'),completed=reviews.filter(r=>r.value.reviewed===today).length;
 const due=words.filter(w=>{const r=reviews.find(r=>r.id===w.word);return r&&str(r.value.next)<=today});
 const fresh=words.filter(w=>!reviews.some(r=>r.id===w.word)).slice(0,Math.max(0,10-completed));
 const current=due[0]||fresh[0];
 async function openBrief(edition:Edition){setSelected(edition);setModal('brief');if(!read.has(edition.date))await save({kind:'read',id:edition.date,value:{read:true}})}
 async function learn(remembered:boolean){if(!current)return;const r=reviews.find(r=>r.id===current.word);const stage=remembered?Math.min(6,Number(r?.value.stage||0)+1):0;const next=new Date(today+'T00:00:00Z');next.setUTCDate(next.getUTCDate()+[1,1,3,7,14,30,60][stage]);if(await save({kind:'word',id:current.word,value:{stage,next:next.toISOString().slice(0,10),reviewed:today}}))setRevealed(false)}
 const taskList=(items:SavedRecord[])=>items.length?items.map(t=><div className="todo" key={t.id}><button className="check" disabled={busy} aria-label={(t.value.done?'撤销完成：':'完成：')+str(t.value.title)} aria-pressed={Boolean(t.value.done)} onClick={()=>void save({kind:'task',id:t.id,value:{title:str(t.value.title),date:str(t.value.date),done:!t.value.done}})}><span>{!!t.value.done&&<Check size={16}/>}</span></button><div className={'todo-text '+(t.value.done?'done':'')}>{str(t.value.title)}<div className="meta">{str(t.value.date)}</div></div>{tab==='日常'&&<button className="quiet" disabled={busy} aria-label="删除待办" onClick={()=>void remove(t)}><Trash2 size={17}/></button>}</div>):<div className="empty">今天还没有安排，给自己留一个小目标吧。<button className="refresh" onClick={()=>setTab('日常')}>添加计划 <Plus size={15}/></button></div>;
 const articleList=(items:Edition['news'])=>items.map((a,i)=><article className="panel article" key={i}><div className="row"><h3>{a.title}</h3><span className={'badge '+(a.status==='已核实'?'':'warning')}>{a.status}</span></div><p>{a.summary}</p>{a.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer">来源 · {s.title} ↗</a>)}</article>);
 const bookCard=latest?<button className="book" onClick={()=>setModal('books')}><span className="book-mark" aria-hidden="true"><BookOpen/><small>BOOK</small></span><span><small>DAILY READING</small><h3>{latest.book.title}</h3><small>{latest.book.author}</small><p>{latest.book.reason.slice(0,55)}{latest.book.reason.length>55?'…':''}</p><span className="link">看看推荐理由 ↗</span></span></button>:<div className="empty">每日一本，和简报一起送达。收到第一份内容后，这里会展示书名与推荐理由。</div>;
 return <main className="app"><div className="content"><header className="row intro"><div><div className="eyebrow">DAYLIGHT / 日序</div><h1>{tab==='今日'?'开启好一天。':tab==='投资'?'让判断更有依据。':tab==='资讯'?'看见值得关注的。':tab==='日常'?'给生活一点秩序。':'每天，前进十个词。'}</h1><div className="greeting">{displayDate(today)}</div></div><button className="icon-button" aria-label={'消息中心，'+unread.length+'条未读'} onClick={()=>setModal('messages')}><Bell/>{unread.length>0&&<span className="unread">{unread.length}</span>}</button></header>
 {error&&<div className="error" role="alert">{error} <button onClick={()=>void load()}>重新连接</button></div>}
 {!loading&&!signedIn&&<section className="panel sign-in"><h2>登录你的日序</h2><p>使用你的 Google 账号登录后，待办、单词和想读会在设备间同步。</p><button className="primary" onClick={()=>void signIn()}>用 Google 登录</button></section>}
 {loading&&<p className="empty" role="status">正在打开你的日序…</p>}
 {tab==='今日'&&<><section className="hero"><div className="row hero-top"><span>你的每日简报</span><span>{latest?(latest.date===today?'今日已送达':latest.date+' · 最近一期'):'等待首份内容'}</span></div><div className="orbit" aria-hidden="true"/><div className="orbit-dot" aria-hidden="true"/><h2>{latest?.title||<>看清世界的变化，<br/>安排自己的节奏。</>}</h2><p>{latest?.introduction||'晨报、精选资讯与每日荐书，\n在这里开始有序的一天。'}</p><div className="row hero-bottom">{latest?<button className="primary" onClick={()=>void openBrief(latest)}>阅读简报 <ArrowUpRight/></button>:<button className="primary" onClick={()=>void load()}>查看更新 <RefreshCw size={16}/></button>}<small>{latest?'来源可追溯':'内容收件箱'}</small></div></section>
 <section className="section"><div className="section-heading"><h2>每天，前进一点</h2><small>YOUR DAILY PULSE</small></div><div className="two"><button className="mini" onClick={()=>setTab('投资')}><div className="row">投资雷达<ArrowUpRight size={16}/></div><strong>{String(stocks.length).padStart(2,'0')}</strong><small>只自选</small><div className="foot">记录关注，沉淀判断</div></button><button className="mini word-tile" onClick={()=>setTab('单词')}><div className="row">每天十个词<BookOpen size={16}/></div><strong>{completed}</strong><small>今日已学</small><div className="track"><i style={{width:Math.min(100,completed/10*100)+'%'}}/></div><div className="foot">{due.length} 词待复习 · 继续学习 →</div></button></div></section>
 <section className="section"><div className="section-heading"><h2>给今天留个计划</h2><button onClick={()=>setTab('日常')}>全部 →</button></div>{taskList(todaysTasks.slice(0,3))}</section>
 <section className="section"><div className="section-heading"><h2>值得一读</h2><button onClick={()=>setTab('资讯')}>更多 →</button></div>{latest?.news.length?latest.news.slice(0,2).map((n,i)=><button className="news" key={i} onClick={()=>setTab('资讯')}><span className="news-icon"><Orbit/></span><span className="news-copy"><h3>{n.title}</h3><small>{latest.date} · {n.status}</small></span><ChevronRight/></button>):<div className="empty">精选资讯正在等候首次送达。</div>}</section>
 <section className="section"><div className="section-heading"><h2>每日一本</h2><button onClick={()=>setModal('books')}>我的想读 {books.length} →</button></div>{bookCard}</section></>}
 {tab==='投资'&&<><section><h2>我的自选</h2><form className="form" onSubmit={async e=>{e.preventDefault();if(await save({kind:'stock',id:stock.toUpperCase(),value:{name:stockName}})){setStock('');setStockName('')}}}><input aria-label="证券代码" placeholder="代码，如 AAPL / 002138" value={stock} onChange={e=>setStock(e.target.value)} required maxLength={20} pattern="[A-Za-z0-9.\^=\-]+"/><input aria-label="公司名称" placeholder="公司名称" value={stockName} onChange={e=>setStockName(e.target.value)} required maxLength={80}/><button className="primary" disabled={busy}>添加</button></form>{stocks.map(s=><div className="panel row" key={s.id}><span>{str(s.value.name)}<small style={{display:'block'}}>{s.id}</small></span><button className="quiet" aria-label={'移除'+str(s.value.name)} onClick={()=>void remove(s)} disabled={busy}><Trash2/></button></div>)}<p className="meta">此处保存关注名单，尚未接入实时行情。</p></section><section className="section"><h2>最新投资观察</h2>{latest?<><p className="meta">{latest.date} · {latest.coveredSession}</p>{articleList(latest.investment)}</>:<div className="empty">收到晨报后展示，有来源的信息才进入你的投资观察。</div>}</section></>}
 {tab==='资讯'&&<><div className="section-heading"><h2>精选资讯</h2><button className="refresh" onClick={()=>void load()}><RefreshCw size={16}/>刷新</button></div>{latest?<><p className="meta">{latest.date} · 最近送达</p>{articleList(latest.news)}</>:<div className="empty">暂时还没有收到资讯，请稍后查看。</div>}<section className="section"><h2>每日一本</h2>{bookCard}</section></>}
 {tab==='日常'&&<><h2>我的计划</h2><form className="form" onSubmit={async e=>{e.preventDefault();if(await save({kind:'task',id:crypto.randomUUID(),value:{title:task,date:today,done:false}}))setTask('')}}><input value={task} onChange={e=>setTask(e.target.value)} placeholder="今天想完成什么？" aria-label="新待办" required maxLength={200}/><button className="primary" disabled={busy}><Plus size={18}/>添加</button></form>{taskList(tasks.slice().sort((a,b)=>str(b.value.date).localeCompare(str(a.value.date))))}<p className="status-note">待办可在登录后的设备间同步；系统日历与定时提醒尚未接入。</p></>}
 {tab==='单词'&&<><div className="section-heading"><h2>日常英语</h2><small>20 词起步词库</small></div><div className="panel word-card"><small>今日已学 {completed} · 到期复习 {due.length}</small>{current?<><div className="word-name">{current.word}</div><button className="secondary" onClick={()=>{if(!('speechSynthesis'in window)){setError('当前浏览器不支持发音');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.word);u.lang='en-US';u.rate=.85;speechSynthesis.speak(u)}} aria-label="播放单词发音"><Volume2/></button>{revealed?<><div className="word-answer"><h3>{current.meaning}</h3><p>{current.example}</p><small>{current.translation}</small></div><div className="word-controls"><button disabled={busy} onClick={()=>void learn(false)}>还不熟悉</button><button className="primary" disabled={busy} onClick={()=>void learn(true)}>记住了 <Check size={17}/></button></div></>:<div style={{marginTop:24}}><button className="primary" onClick={()=>setRevealed(true)}>看看释义</button></div>}</>:<><div className="word-name">Well done.</div><p>今天的学习已完成。</p><small>明天再来看看需要复习的词。</small></>}</div><p className="meta">先复习，再学新词。每天最多 10 个新词，学习进度会保存到你的账户。</p></>}
 <p className="status-note">私人空间 · 北京时间<br/>系统推送尚未接入；打开页面后自动检查更新。</p></div>
 <nav className="bottom-nav" aria-label="主导航">{navigation.map(([name,Icon])=><button key={name} aria-current={tab===name?'page':undefined} onClick={()=>{setTab(name);window.scrollTo({top:0})}}><span><Icon/></span>{name}</button>)}</nav>
 <dialog className="sheet" ref={dialog} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null)}}><div className="row top"><div className="eyebrow">DAYLIGHT / 日序</div><button className="icon-button" aria-label="关闭详情" onClick={()=>setModal(null)}><X/></button></div>{modal==='brief'&&selected&&<><h2>{selected.title}</h2><p>{selected.date} · {selected.coveredSession}</p><p>{selected.introduction}</p><h3>投资观察</h3>{articleList(selected.investment)}<h3>精选资讯</h3>{articleList(selected.news)}<small>内容供阅读与研究，请结合原始来源判断。</small></>}{modal==='messages'&&<><h2>消息中心</h2><p>最近 30 期 · {unread.length} 期未读</p>{data.editions.length?data.editions.map(e=><button className="history-button" key={e.date} onClick={()=>void openBrief(e)}><small>{e.date} · {read.has(e.date)?'已读':'未读'}</small><h3>{e.title}</h3></button>):<p>还没有收到内容。第一份简报送达后，会出现在这里。</p>}</>}{modal==='books'&&<><h2>每日一本</h2>{latest?<><p>{latest.date} · {latest.book.author}</p><h2>{latest.book.title}</h2><p>{latest.book.reason}</p><div className="panel">阅读小提议<p>{latest.book.prompt}</p></div><a href={latest.book.source.url} target="_blank" rel="noopener noreferrer">书籍资料 · {latest.book.source.title} ↗</a><button className="primary" disabled={busy||books.some(b=>b.id===latest.date)} onClick={()=>void save({kind:'book',id:latest.date,value:{title:latest.book.title,author:latest.book.author,reason:latest.book.reason,url:latest.book.source.url}})}><Bookmark size={17}/>{books.some(b=>b.id===latest.date)?'已加入想读':'加入想读'}</button></>:<p>今日荐书尚未送达。</p>}<h3 style={{marginTop:24}}>我的想读 · {books.length}</h3>{books.map(b=><div className="panel row" key={b.id}><span>{str(b.value.title)}<small style={{display:'block'}}>{str(b.value.author)}</small></span><button className="quiet" aria-label="移出想读" onClick={()=>void remove(b)} disabled={busy}><Trash2/></button></div>)}</>}</dialog>
 </main>
}
