export const words = [
  ['perspective','观点；视角','A new day brings a fresh perspective.','新的一天带来新的视角。'],
  ['curious','好奇的','Stay curious about the world.','保持对世界的好奇。'],
  ['habit','习惯','Reading is a daily habit.','阅读是一个日常习惯。'],
  ['balance','平衡','Find a balance between work and rest.','找到工作与休息之间的平衡。'],
  ['focus','专注','Focus on one thing at a time.','一次专注于一件事。'],
  ['patient','有耐心的','Be patient with yourself.','对自己有耐心。'],
  ['reflect','反思','Take time to reflect on your day.','花点时间回顾你的一天。'],
  ['discover','发现','Discover something new today.','今天发现一点新东西。'],
  ['improve','改善；提高','Small steps can improve your life.','小小的行动能改善生活。'],
  ['consistent','始终如一的','Consistent practice makes a difference.','持续练习会带来改变。'],
  ['evidence','证据','Look for evidence before making a decision.','做决定前先寻找证据。'],
  ['opportunity','机会','Every challenge is an opportunity to learn.','每个挑战都是学习的机会。'],
  ['uncertain','不确定的','The result is still uncertain.','结果仍然不确定。'],
  ['value','价值','Time with family has great value.','与家人共处的时间很有价值。'],
  ['research','研究','Good research begins with a clear question.','好的研究始于一个清晰的问题。'],
  ['consider','考虑','Consider a different approach.','考虑一种不同的方法。'],
  ['compare','比较','Compare the options carefully.','仔细比较各种选择。'],
  ['essential','必要的','Sleep is essential for good health.','睡眠对健康至关重要。'],
  ['gradually','逐渐地','Your confidence will grow gradually.','你的信心会逐渐增长。'],
  ['routine','日常惯例','A simple routine helps me start the day.','简单的日常安排帮助我开启一天。'],
].map(([word,meaning,example,translation])=>({word,meaning,example,translation}));
